### ISSUE TITLE
create_taxonomy_count_dataframe.py only works on proGenomes

### ISSUE THREAD

**Issue by boulund** [boulund/wellness_wgs#1]
It seems create_taxonomy_count_dataframe.py doesn't work on samples run using Kaiju's `nr_euk` database.

**Comment by Steffi17** [comment]
```
./create_taxonomy_count_dataframe.py kaiju_FA.*species               
Traceback (most recent call last):
  File "./create_taxonomy_count_dataframe.py", line 71, in <module>
    main(options.KAIJU, options.output, options.lineage)
  File "./create_taxonomy_count_dataframe.py", line 54, in main
    combined_df = pd.concat(sample_dfs, axis=1)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 207, in concat
    return op.get_result()
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 384, in get_result
    df = cons(data, index=index)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 275, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 411, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 5599, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 5898, in _homogenize
    v = v.reindex(index, copy=False)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/series.py", line 2426, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 2404, in reindex
    fill_value, copy).__finalize__(self)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 2422, in _reindex_axes
    copy=copy, allow_dups=False)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 2516, in _reindex_with_indexers
    copy=copy)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2787, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```
